# Generated by Django 4.0.1 on 2022-02-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wiadomosc',
            options={'ordering': ['created_date'], 'verbose_name': 'wiadomość', 'verbose_name_plural': 'wiadomości'},
        ),
        migrations.RenameField(
            model_name='wiadomosc',
            old_name='body',
            new_name='tekst',
        ),
    ]
